### ISSUE TITLE
Error Interface is not up in v0.4.2

### ISSUE THREAD

**Issue by claudio4** [kube-vip/kube-vip#385]
**Describe the bug**
Kube-vip refuses to start arguing that the interface is not up, but it is. Furthermore, doing exactly the same steps but using v0.4.0 instead of v0.4.2 works flawlessly.

**To Reproduce**
1. Create a manifest using `ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.4.2 vip /kube-vip manifest pod --interface ens33 --address 192.168.140.200 --controlplane --arp --leaderElection` and place it /etc/kubernetes/manifests/kube-vip.yaml
2. Init the cluster with `kubeadm init --config kubeadm-init.yml --upload-certs` (config file provided at the end of the issue)
3. When the installation fails check the container logs with `crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID`

The log will show something like this
```
time="2022-03-29T07:59:55Z" level=fatal msg="ens33 is not valid interface, reason: ens33 is not up"
```
**Expected behavior**
I expect it to work normally, as it does with v0.4.0

**Environment (please complete the following information):**
 - OS/Distro: Flatcar 3033.2.4
 - Kubernetes Version: v1.23.5
 - Kube-vip Version: v0.4.2

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens33
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.140.200
    image: ghcr.io/kube-vip/kube-vip:v0.4.2
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```
**` kubeadm-init.yml`:***
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.140.200:6443"
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```
**Extra context**
This looks similar to #360.

Thank you for this great application.

**Comment by thebsdbox** [comment]
Hello can you show the results of: 
` ip link show ens33` and `ip address show ens33`
Thanks

**Comment by claudio4** [comment]
Sure.
`ip link show ens33`:
```
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:b3:ba:0f brd ff:ff:ff:ff:ff:ff
    altname enp2s1
```
`ip address show ens33`:
```
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:0c:29:b3:ba:0f brd ff:ff:ff:ff:ff:ff
    altname enp2s1
    inet 192.168.140.146/24 metric 1024 brd 192.168.140.255 scope global dynamic ens33
       valid_lft 1748sec preferred_lft 1748sec
    inet6 fe80::20c:29ff:feb3:ba0f/64 scope link
       valid_lft forever preferred_lft forever
```

Also, i want to expand with a little more context:
* This interface belongs to a VM in VMWare.
* The whole network is inside VMWare.
* The IP 192.168.140.200 is not in use by any other machine in the network.

**Comment by thebsdbox** [comment]
![image](https://user-images.githubusercontent.com/1658918/162241748-d1458ce5-afcf-4ac0-a897-aa39de216b14.png)
Is the output from a flatcar OVA I just deployed.

**Comment by claudio4** [comment]
Yes, you are right, changing the adapter type to e1000 allowed flatcar to detect the UP state and with that kube-vip installed without complaint. Interestingly enough, the VMware OVA uses the VMXNET3 and detects the UP state correctly, this does not happen with ISO installs even if the VMware raw image is selected.

A question remains, does kube-vip really need to check for the UP state in the interface?  In my opinion, keeping the check like this will generate a constant stream of duplicated issues similar to this one, where users with quirky network interfaces will report that they can't install kube-vip. 

Possible solutions to this are:
* Test whether checking for LOWER_UP suffices, as it looks like it's reported a lot more consistently than UP.
* Accept UNKOWN as valid state and perhaps report a warning.
*  Introduce an option to disable this check and inform the user about this option when the error is triggered (a la [kubeadm preflight check](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#preflight-checks-1)).

**Comment by thebsdbox** [comment]
I'm hoping #388 might fix this if not, I'm sure we can come up with a patch.

**Comment by claudio4** [comment]
I just tested it with the main image and the issue persists.  But I think I can make a PR with a fix later today or maybe tomorrow.

**Comment by thebsdbox** [comment]
It should have been merged into the `nightly`?

**Comment by mkumatag** [comment]
I'm seeing the same issue in one of our machine as well for env2, using `docker.io/plndr/kube-vip:v0.4.3`

```
[root@ibm-powervs-1-control-plane-wvt6w mkumatag]# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: env2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether fa:9e:60:e6:21:20 brd ff:ff:ff:ff:ff:ff
    inet 192.168.132.86/29 brd 192.168.132.87 scope global noprefixroute env2
       valid_lft forever preferred_lft forever
    inet 192.168.132.84/32 scope global env2
       valid_lft forever preferred_lft forever
    inet6 fe80::f89e:60ff:fee6:2120/64 scope link
       valid_lft forever preferred_lft forever
```
