### ISSUE TITLE
Daemonset manifest generation documentation 404

### ISSUE THREAD

**Issue by franbocca** [kube-vip/kube-vip#525]
Hi, I am following the install steps to setup a HA K3s cluster on this page [Step 3: Generate a kube-vip DaemonSet Manifest](https://kube-vip.io/docs/usage/k3s/#step-3-generate-a-kube-vip-daemonset-manifest), but the [DaemonSet manifest generation documentation](https://kube-vip.io/install_daemonset/#generating-a-manifest) link is broken showing a 404. Could you please help me to get information on how to generate that Daemonset? Thanks

1. Go to https://kube-vip.io/docs/usage/k3s/#step-3-generate-a-kube-vip-daemonset-manifest
2. Click on DaemonSet manifest generation documentation
3. See error 404 on page

Expected behavior
Page showing instructions on how to generate a DaemonSet manifest for K3s.

Regards

**Comment by thebsdbox** [comment]
This has been fixed

**Comment by lubronzhan** [comment]
This is weird. I verified locally with markdown, https://github.com/lubronzhan/website/blob/0e7b3230661eab5d1a7d7d7e081b0c982f1f56ad/content/docs/usage/k3s.md Also the redirect works on the preview.
But on the website it's still not working
https://kube-vip.io/content/docs/installation/flags.md
https://kube-vip.io/content/docs/installation/daemonset.md#generating-a-manifest
I also broke the other link. Looks like content is not needed for the website. only needed for markdown. Let me fix it again...

**Comment by franbocca** [comment]
Yes, for some reason the website has not been updated, though I see the md
working.

Regards,
